name: Tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: main
  cancel-in-progress: false

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Static Analysis
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run pre-commit
        run: make test/pre-commit
